coverage:
  status:
    project:
      default:
        target: 75%
        threshold: null
        base: auto

comment: false

ignore:
  - "src/testing/"
  - "common/"
  - "e2e/"
  - "mockData/"
  - "node_modules/"
