dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js

cache:
  directories:
     - ./node_modules

before_install:
- npm install -g @angular/cli
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- ng test --watch=false

branches:
  only:
    - master
